package com.mycompany.server;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class ServerDialog extends javax.swing.JDialog {

    /**
     * Creates new form DiscoverDialog
     */
    private String peerID, command;
    private Server server;
    private Map<String, PeerHandler> peerHandlers = new HashMap<>();

    public ServerDialog(java.awt.Frame parent, boolean modal, String peerID, String command, Server server) {
        super(parent, modal);
        initComponents();
        this.peerID = peerID;
        this.command = command;
        btnCommand.setText(command);
        panelSharedFiles.setVisible(this.command.equals("Discover"));
        txtPeerID.setText(peerID);
        this.server = server;

        // Calculate the center position based on the parent frame
        int parentX = parent.getX();
        int parentY = parent.getY();
        int parentWidth = parent.getWidth();
        int parentHeight = parent.getHeight();

        int dialogX = parentX + (parentWidth - this.getWidth()) / 2;
        int dialogY = parentY + (parentHeight - this.getHeight()) / 2;

        // Set the dialog location
        this.setLocation(dialogX, dialogY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPeerID = new javax.swing.JTextField();
        btnCommand = new javax.swing.JButton();
        lablePeerID = new javax.swing.JLabel();
        panelSharedFiles = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSharedFiles = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtPeerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeerIDActionPerformed(evt);
            }
        });

        btnCommand.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCommand.setText("Discover");
        btnCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommandActionPerformed(evt);
            }
        });

        lablePeerID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lablePeerID.setText("Peer ID");

        panelSharedFiles.setBorder(javax.swing.BorderFactory.createTitledBorder("Shared files"));

        listSharedFiles.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(listSharedFiles);

        javax.swing.GroupLayout panelSharedFilesLayout = new javax.swing.GroupLayout(panelSharedFiles);
        panelSharedFiles.setLayout(panelSharedFilesLayout);
        panelSharedFilesLayout.setHorizontalGroup(
            panelSharedFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSharedFilesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelSharedFilesLayout.setVerticalGroup(
            panelSharedFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSharedFilesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lablePeerID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(txtPeerID, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCommand)
                        .addGap(18, 18, 18)
                        .addComponent(panelSharedFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lablePeerID)
                    .addComponent(txtPeerID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCommand)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelSharedFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPeerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeerIDActionPerformed

    private void btnCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommandActionPerformed
        // TODO add your handling code here:

        if (this.command.equals("Discover")) {
            DefaultListModel listModel = (DefaultListModel) listSharedFiles.getModel();
            listModel.removeAllElements();
            this.server.discoverAction(txtPeerID.getText());
        } else {
            this.server.pingAction(txtPeerID.getText());
        }
    }//GEN-LAST:event_btnCommandActionPerformed

    public void addFileToList(String fileName) {
        DefaultListModel listModel = (DefaultListModel) listSharedFiles.getModel();
        listModel.addElement(fileName);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCommand;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lablePeerID;
    private javax.swing.JList<String> listSharedFiles;
    private javax.swing.JPanel panelSharedFiles;
    private javax.swing.JTextField txtPeerID;
    // End of variables declaration//GEN-END:variables
}
